services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    container_name: elk-elasticsearch-1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - elk_esdata:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.0
    container_name: elk-kibana-1
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    volumes:
      - elk_kibanadata:/usr/share/kibana/data

volumes:
  elk_esdata:
    driver: local
    driver_opts:
      type: none
      device: /home/baouabli/elk-data/es
      o: bind

  elk_kibanadata:
    driver: local
    driver_opts:
      type: none
      device: /home/baouabli/elk-data/kibana
      o: bind
